-- 1. Users Table Upgrade (Profile Details)
ALTER TABLE public.users 
ADD COLUMN IF NOT EXISTS gender text check (gender in ('male', 'female')),
ADD COLUMN IF NOT EXISTS age int,
ADD COLUMN IF NOT EXISTS activity_level numeric,
ADD COLUMN IF NOT EXISTS target_weight numeric;

-- 2. Food Logs Upgrade (AI Analysis Data)
ALTER TABLE public.food_logs
ADD COLUMN IF NOT EXISTS health_score int,
ADD COLUMN IF NOT EXISTS burn_activity text,
ADD COLUMN IF NOT EXISTS pros text,
ADD COLUMN IF NOT EXISTS cons text;

-- 3. Weight History Table (New)
-- To track weight changes over time
CREATE TABLE IF NOT EXISTS public.weight_logs (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    weight numeric not null,
    date date default timezone('utc'::text, now())::date not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for weight_logs
ALTER TABLE public.weight_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert their own weight logs" 
ON public.weight_logs FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own weight logs" 
ON public.weight_logs FOR SELECT 
USING (auth.uid() = user_id);
